import React from 'react';
import {
  Activity,
  AudioLines,
  BarChart3,
  Bot,
  Box,
  Boxes,
  CalendarClock,
  Code2,
  Container,
  Cpu,
  CreditCard,
  Database,
  FileCode,
  FileEdit,
  FileSearch,
  FileText,
  Film,
  Folder,
  FolderTree,
  Folders,
  Gauge,
  GitBranch,
  Hammer,
  HardDrive,
  History,
  Home,
  Languages,
  Layers,
  LayoutList,
  LayoutTemplate,
  Library,
  Link,
  ListChecks,
  ListTodo,
  MessageSquare,
  MessagesSquare,
  Package,
  BookOpen,
  Search,
  Settings,
  Shield,
  Monitor,
  Network,
  PlayCircle,
  Receipt,
  Rocket,
  ScrollText,
  Server,
  ServerCog,
  SlidersHorizontal,
  Sparkles,
  Store,
  Table,
  Tags,
  UserCog,
  Users,
  Wallet,
  Waypoints,
  Workflow,
  Image,
  LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'audio-lines': AudioLines,
  'bar-chart': BarChart3,
  bot: Bot,
  box: Box,
  boxes: Boxes,
  'calendar-clock': CalendarClock,
  code: Code2,
  container: Container,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  'file-code': FileCode,
  'file-edit': FileEdit,
  'file-search': FileSearch,
  'file-text': FileText,
  film: Film,
  folder: Folder,
  'folder-tree': FolderTree,
  folders: Folders,
  gauge: Gauge,
  'git-branch': GitBranch,
  hammer: Hammer,
  'hard-drive': HardDrive,
  history: History,
  home: Home,
  image: Image,
  languages: Languages,
  layers: Layers,
  'layout-list': LayoutList,
  'layout-template': LayoutTemplate,
  library: Library,
  link: Link,
  'list-checks': ListChecks,
  'list-todo': ListTodo,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  package: Package,
  'book-open': BookOpen,
  search: Search,
  settings: Settings,
  shield: Shield,
  monitor: Monitor,
  network: Network,
  'play-circle': PlayCircle,
  receipt: Receipt,
  rocket: Rocket,
  'scroll-text': ScrollText,
  server: Server,
  'server-cog': ServerCog,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  store: Store,
  table: Table,
  tags: Tags,
  'user-cog': UserCog,
  users: Users,
  wallet: Wallet,
  waypoints: Waypoints,
  workflow: Workflow,
};

export function MenuGlyph({ name }: { name: string }) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon className="mo-menu-icon" size={18} strokeWidth={2} absoluteStrokeWidth aria-hidden />;
}

export function renderMenuIcon(icon: unknown) {
  if (typeof icon === 'string' && icon.startsWith('lucide:')) {
    return <MenuGlyph name={icon.slice('lucide:'.length)} />;
  }
  if (typeof icon === 'string') {
    return <span className="icon-custom svg16 mr8" dangerouslySetInnerHTML={{ __html: icon }} />;
  }
  return icon as React.ReactNode;
}
