apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: dev
spec:
  hosts:
  - {name: REPLACE_WITH_NODE_1_IP, address: REPLACE_WITH_NODE_1_IP, internalAddress: REPLACE_WITH_NODE_1_IP, port: 22, user: REPLACE_WITH_SSH_USER, password: "REPLACE_WITH_PRIVATE_SSH_PASSWORD"}
  - {name: REPLACE_WITH_NODE_2_IP, address: REPLACE_WITH_NODE_2_IP, internalAddress: REPLACE_WITH_NODE_2_IP, port: 22, user: REPLACE_WITH_SSH_USER, password: "REPLACE_WITH_PRIVATE_SSH_PASSWORD"}
  # arm  - {name: REPLACE_WITH_NODE_2_IP, address: REPLACE_WITH_NODE_2_IP, internalAddress: REPLACE_WITH_NODE_2_IP, port: 22, user: REPLACE_WITH_SSH_USER, password: "REPLACE_WITH_PRIVATE_SSH_PASSWORD", arch: arm64}
  roleGroups:
    etcd:
    - REPLACE_WITH_NODE_1_IP
    control-plane:
    - REPLACE_WITH_NODE_1_IP
    worker:
    - REPLACE_WITH_NODE_1_IP
    - REPLACE_WITH_NODE_2_IP
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.25.16
    proxyMode: iptables
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
    apiserverArgs:
      - service-node-port-range=1-65535
    kubelet:
      serializeImagePulls: false   # 设置为false允许并行拉取镜像
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.0.0/16
    kubeServiceCIDR: 10.234.0.0/16
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  addons: []
