apiVersion: v1
stringData:
  user: admin
  password: REPLACE_WITH_PRIVATE_GRAFANA_PASSWORD
  secretKey: REPLACE_WITH_PRIVATE_GRAFANA_SECRET_KEY
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
